# visit https://github.com/mojombo/jekyll/wiki/Configuration for more settings

paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
highlighter: rouge
markdown: kramdown
disqus: https-nomzaxs-github-io
google_analytics: G-YBCZ1NTNFG
title: moca
future: true

defaults:
  -
    scope:
      path: "" # empty string for all files
    values:
      title: 커피 좋아하는 개발 블로그

description: Stylish Jekyll Theme
author:
  name: Moca
  email: nomzaxs@gmail.com
  github: nomzaxs
  instagram: s_hyxn
  bio: 커피 좋아하는 개발 블로그
  email_md5: 0af15cc911887bd24e445cdd4c9e962b

rss_path: feed.xml
categories_path: categories.html
tags_path: tags.html

# set it as url of an image
# sidebar_background_image: https://www.dropbox.com/s/g9h23zrycedxtk5/sky.png?raw=1

BASE_PATH:

plugins:
  - jekyll-paginate
